spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://postgres-delivery:5432/delivery_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  secret: ${JWT_SECRET_KEY}
internal:
  service:
    token: ${INTERNAL_SERVICE_TOKEN}
