spring.application.name=delivery-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8087

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT
jwt.secret=${JWT_SECRET_KEY}
internal.service.token=${INTERNAL_SERVICE_TOKEN}

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persistAuthorization=true

# Circuit Breaker
resilience4j.circuitbreaker.instances.delivery-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.delivery-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.delivery-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.delivery-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.delivery-service.permitted-number-of-calls-in-half-open-state=3
spring.cloud.openfeign.circuitbreaker.enabled=true
feign.circuitbreaker.enabled=true
spring.cloud.openfeign.circuitbreaker.alphanumeric-ids.enabled=true
resilience4j.circuitbreaker.instances.order-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.order-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.order-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.order-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.order-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.timelimiter.instances.order-service.timeout-duration=3s

# Actuator
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,circuitbreakers,prometheus,info

# RabbitMQ listener retry
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2